on:
  [pull_request, push]

name: Check

jobs:
  pipeline:
    name: Pipeline Stack
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Synthesize
        run: |
          cd pipeline/
          npm install -g aws-cdk

          python3 -m venv .venv
          source .venv/bin/activate
          pip install -r requirements.txt
          pip install -r requirements-dev.txt

          pytest

  stacks:
    name: Application Stacks
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: 18
    - uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    - name: Synthesize
      run: |
        npm install -g aws-cdk

        python3 -m venv .venv
        source .venv/bin/activate
        pip install -r requirements.txt
        pip install -r requirements-dev.txt

        pytest test_cdk_stacks.py
        cd techniques_bedrock_flows
        pytest
        cd ../techniques_step_functions
        pytest
